-- Carga inicial de stock: los 43 productos reales, 5 unidades cada uno.
-- Correr una sola vez, despues de schema.sql.
insert into stock (id, nombre, cantidad) values
  (2, 'Cartera Beige Tejida', 5),
  (3, 'Cartera Naranja Compacta', 5),
  (4, 'Cartera Vino Abovedada', 5),
  (5, 'Cartera Blanca Acolchada', 5),
  (6, 'Cartera Beige Acolchada', 5),
  (7, 'Satchel Violeta Ejecutiva', 5),
  (8, 'Mini Bandolera Pastel', 5),
  (9, 'Cartera Rosa Casual', 5),
  (10, 'Satchel Cuero Cognac', 5),
  (11, 'Clutch Negra Cadena Dorada', 5),
  (12, 'Clutch Negra Elegante', 5),
  (13, 'Tote Camel Minimalista', 5),
  (14, 'Clutch Blanco Satinado', 5),
  (15, 'Bucket Negro Tejido con Flores', 5),
  (16, 'Mini Clutch Café Elegante', 5),
  (17, 'Tote Canvas Café', 5),
  (18, 'Clutch Azul Cielo', 5),
  (19, 'Satchel Cognac Doble Correa', 5),
  (20, 'Bandolera Café Clásica', 5),
  (21, 'Bucket Beige Tejido Artesanal', 5),
  (22, 'Mini Clutch Rojo Dorado', 5),
  (23, 'Bandolera Vino Crossbody', 5),
  (24, 'Satchel Estructurada Clásica', 5),
  (25, 'Cartera Terracota Minimal', 5),
  (26, 'Mini Clutch Colección Pastel', 5),
  (27, 'Cartera Roja Acolchada', 5),
  (28, 'Satchel Café Multibolsillo', 5),
  (29, 'Bandolera Vaquetilla Animal Print', 5),
  (30, 'Bucket Playero Rafia Natural', 5),
  (31, 'Mini Bolso Floral Azul', 5),
  (32, 'Clutch Tapiz Floral Vintage', 5),
  (33, 'Tote Blanco Colgado', 5),
  (34, 'Cartera Gris Bicolor', 5),
  (35, 'Tote Negro Minimalista', 5),
  (36, 'Satchel Cognac Doble Hebilla', 5),
  (37, 'Mini Bolso Ciruela Elegante', 5),
  (38, 'Bucket Tejido Playero', 5),
  (39, 'Cartera Beige y Blanca', 5),
  (40, 'Satchel Verde Oliva y Cuero', 5),
  (41, 'Bandolera Blanca Cadena Dorada', 5),
  (42, 'Bucket Camel Bordado Boho', 5),
  (43, 'Mini Bolso Negro Acolchado', 5),
  (44, 'Clutch Rojo Fiesta', 5)
on conflict (id) do nothing;
