const productos = [
  { id: 1, nombre: "Monedero Coral Cerezas", precio: 28.99, img: "img/reales/cartera-real-51.jpg", categoria: "mini" },
  { id: 2, nombre: "Cartera Beige Tejida", precio: 32.50, img: "img/reales/cartera-real-21.jpg", categoria: "hombro" },
  { id: 3, nombre: "Cartera Naranja Compacta", precio: 25.00, img: "img/reales/cartera-real-22.jpg", categoria: "hombro" },
  { id: 4, nombre: "Cartera Vino Abovedada", precio: 29.99, img: "img/reales/cartera-real-23.jpg", categoria: "hombro" },
  { id: 5, nombre: "Cartera Blanca Acolchada", precio: 31.00, img: "img/reales/cartera-real-24.jpg", categoria: "hombro" },
  { id: 6, nombre: "Cartera Beige Acolchada", precio: 27.50, img: "img/reales/cartera-real-25.jpg", categoria: "hombro" },
  { id: 7, nombre: "Satchel Violeta Ejecutiva", precio: 35.99, img: "img/reales/cartera-real-1.jpg", categoria: "satchel" },
  { id: 8, nombre: "Mini Bandolera Pastel", precio: 23.50, img: "img/reales/cartera-real-2.jpg", categoria: "bandolera" },
  { id: 9, nombre: "Cartera Rosa Casual", precio: 24.99, img: "img/reales/cartera-real-5.jpg", categoria: "hombro" },
  { id: 10, nombre: "Satchel Cuero Cognac", precio: 38.00, img: "img/reales/cartera-real-6.jpg", categoria: "satchel" },
  { id: 11, nombre: "Clutch Negra Cadena Dorada", precio: 29.99, img: "img/reales/cartera-real-7.jpg", categoria: "clutch" },
  { id: 12, nombre: "Clutch Negra Elegante", precio: 27.50, img: "img/reales/cartera-real-8.jpg", categoria: "clutch" },
  { id: 13, nombre: "Tote Camel Minimalista", precio: 26.99, img: "img/reales/cartera-real-32.jpg", categoria: "tote" },
  { id: 14, nombre: "Clutch Blanco Satinado", precio: 22.99, img: "img/reales/cartera-real-37.jpg", categoria: "clutch" },
  { id: 15, nombre: "Bucket Negro Tejido con Flores", precio: 30.50, img: "img/reales/cartera-real-40.jpg", categoria: "bucket" },
  { id: 16, nombre: "Mini Clutch Café Elegante", precio: 25.99, img: "img/reales/cartera-real-46.jpg", categoria: "mini" },
  { id: 17, nombre: "Tote Canvas Café", precio: 21.99, img: "img/reales/cartera-real-9.jpg", categoria: "tote" },
  { id: 18, nombre: "Clutch Azul Cielo", precio: 33.00, img: "img/reales/cartera-real-11.jpg", categoria: "clutch" },
  { id: 19, nombre: "Satchel Cognac Doble Correa", precio: 34.99, img: "img/reales/cartera-real-29.jpg", categoria: "satchel", nuevo: true },
  { id: 20, nombre: "Bandolera Café Clásica", precio: 26.50, img: "img/reales/cartera-real-34.jpg", categoria: "bandolera", nuevo: true },
  { id: 21, nombre: "Bucket Beige Tejido Artesanal", precio: 31.99, img: "img/reales/cartera-real-41.jpg", categoria: "bucket", nuevo: true },
  { id: 22, nombre: "Mini Clutch Rojo Dorado", precio: 23.99, img: "img/reales/cartera-real-47.jpg", categoria: "mini", nuevo: true },
  { id: 23, nombre: "Bandolera Vino Crossbody", precio: 28.50, img: "img/reales/cartera-real-12.jpg", categoria: "bandolera", nuevo: true },
  { id: 24, nombre: "Satchel Estructurada Clásica", precio: 36.99, img: "img/reales/cartera-real-13.jpg", categoria: "satchel", nuevo: true },
  { id: 25, nombre: "Cartera Terracota Minimal", precio: 27.99, img: "img/reales/cartera-real-14.jpg", categoria: "hombro", nuevo: true },
  { id: 26, nombre: "Mini Clutch Colección Pastel", precio: 24.50, img: "img/reales/cartera-real-15.jpg", categoria: "mini", nuevo: true },
  { id: 27, nombre: "Cartera Roja Acolchada", precio: 29.50, img: "img/reales/cartera-real-26.jpg", categoria: "hombro", nuevo: true },
  { id: 28, nombre: "Satchel Café Multibolsillo", precio: 33.99, img: "img/reales/cartera-real-30.jpg", categoria: "satchel", nuevo: true },
  { id: 29, nombre: "Bandolera Vaquetilla Animal Print", precio: 27.99, img: "img/reales/cartera-real-35.jpg", categoria: "bandolera", nuevo: true },
  { id: 30, nombre: "Bucket Playero Rafia Natural", precio: 30.99, img: "img/reales/cartera-real-42.jpg", categoria: "bucket", nuevo: true },
  { id: 31, nombre: "Mini Bolso Floral Azul", precio: 22.99, img: "img/reales/cartera-real-49.jpg", categoria: "mini", nuevo: true },
  { id: 32, nombre: "Clutch Tapiz Floral Vintage", precio: 28.99, img: "img/reales/cartera-real-38.jpg", categoria: "clutch", nuevo: true },
  { id: 33, nombre: "Tote Blanco Colgado", precio: 24.50, img: "img/reales/cartera-real-48.jpg", categoria: "tote", nuevo: true },
  { id: 34, nombre: "Cartera Gris Bicolor", precio: 31.50, img: "img/reales/cartera-real-27.jpg", categoria: "hombro", nuevo: true },
  { id: 35, nombre: "Tote Negro Minimalista", precio: 25.99, img: "img/reales/cartera-real-16.jpg", categoria: "tote", nuevo: true },
  { id: 36, nombre: "Satchel Cognac Doble Hebilla", precio: 37.50, img: "img/reales/cartera-real-17.jpg", categoria: "satchel", nuevo: true },
  { id: 37, nombre: "Mini Bolso Ciruela Elegante", precio: 29.99, img: "img/reales/cartera-real-18.jpg", categoria: "mini", nuevo: true },
  { id: 38, nombre: "Bucket Tejido Playero", precio: 26.99, img: "img/reales/cartera-real-19.jpg", categoria: "bucket", nuevo: true },
  { id: 39, nombre: "Cartera Beige y Blanca", precio: 28.50, img: "img/reales/cartera-real-28.jpg", categoria: "hombro", nuevo: true },
  { id: 40, nombre: "Satchel Verde Oliva y Cuero", precio: 34.50, img: "img/reales/cartera-real-31.jpg", categoria: "satchel", nuevo: true },
  { id: 41, nombre: "Bandolera Blanca Cadena Dorada", precio: 27.99, img: "img/reales/cartera-real-36.jpg", categoria: "bandolera", nuevo: true },
  { id: 42, nombre: "Bucket Camel Bordado Boho", precio: 30.50, img: "img/reales/cartera-real-43.jpg", categoria: "bucket", nuevo: true },
  { id: 43, nombre: "Mini Bolso Negro Acolchado", precio: 23.50, img: "img/reales/cartera-real-50.jpg", categoria: "mini", nuevo: true },
  { id: 44, nombre: "Clutch Rojo Fiesta", precio: 26.99, img: "img/reales/cartera-real-39.jpg", categoria: "clutch", nuevo: true },
];
