const productos = [
  { id: 1, nombre: "Cartera Coral Sunset", precio: 28.99, img: "img/cartera1.svg", categoria: "hombro" },
  { id: 2, nombre: "Cartera Violeta Fiesta", precio: 32.50, img: "img/cartera2.svg", categoria: "hombro" },
  { id: 3, nombre: "Cartera Dorado Atardecer", precio: 25.00, img: "img/cartera3.svg", categoria: "hombro" },
  { id: 4, nombre: "Cartera Turquesa Fresca", precio: 29.99, img: "img/cartera4.svg", categoria: "hombro" },
  { id: 5, nombre: "Cartera Rosa Neón", precio: 31.00, img: "img/cartera5.svg", categoria: "hombro" },
  { id: 6, nombre: "Cartera Azul Real", precio: 27.50, img: "img/cartera6.svg", categoria: "hombro" },
  { id: 7, nombre: "Satchel Violeta Ejecutiva", precio: 35.99, img: "img/reales/cartera-real-1.jpg", categoria: "satchel" },
  { id: 8, nombre: "Mini Bandolera Pastel", precio: 23.50, img: "img/reales/cartera-real-2.jpg", categoria: "bandolera" },
  { id: 9, nombre: "Cartera Rosa Casual", precio: 24.99, img: "img/reales/cartera-real-5.jpg", categoria: "hombro" },
  { id: 10, nombre: "Satchel Cuero Cognac", precio: 38.00, img: "img/reales/cartera-real-6.jpg", categoria: "satchel" },
  { id: 11, nombre: "Clutch Negra Cadena Dorada", precio: 29.99, img: "img/reales/cartera-real-7.jpg", categoria: "clutch" },
  { id: 12, nombre: "Clutch Negra Elegante", precio: 27.50, img: "img/reales/cartera-real-8.jpg", categoria: "clutch" },
  { id: 13, nombre: "Tote Turquesa Aventura", precio: 26.99, img: "img/cartera13.svg", categoria: "tote" },
  { id: 14, nombre: "Clutch Atardecer Dorado", precio: 22.99, img: "img/cartera14.svg", categoria: "clutch" },
  { id: 15, nombre: "Bucket Bag Violeta Noche", precio: 30.50, img: "img/cartera15.svg", categoria: "bucket" },
  { id: 16, nombre: "Mini Bolso Cadena Fuego", precio: 25.99, img: "img/cartera16.svg", categoria: "mini" },
  { id: 17, nombre: "Tote Canvas Café", precio: 21.99, img: "img/reales/cartera-real-9.jpg", categoria: "tote" },
  { id: 18, nombre: "Clutch Azul Cielo", precio: 33.00, img: "img/reales/cartera-real-11.jpg", categoria: "clutch" },
  { id: 19, nombre: "Satchel Esmeralda Urbana", precio: 34.99, img: "img/cartera19.svg", categoria: "satchel", nuevo: true },
  { id: 20, nombre: "Bandolera Coral Atardecer", precio: 26.50, img: "img/cartera20.svg", categoria: "bandolera", nuevo: true },
  { id: 21, nombre: "Bucket Bag Índigo Profundo", precio: 31.99, img: "img/cartera21.svg", categoria: "bucket", nuevo: true },
  { id: 22, nombre: "Mini Bolso Verde Menta", precio: 23.99, img: "img/cartera22.svg", categoria: "mini", nuevo: true },
  { id: 23, nombre: "Bandolera Vino Crossbody", precio: 28.50, img: "img/reales/cartera-real-12.jpg", categoria: "bandolera", nuevo: true },
  { id: 24, nombre: "Satchel Estructurada Clásica", precio: 36.99, img: "img/reales/cartera-real-13.jpg", categoria: "satchel", nuevo: true },
  { id: 25, nombre: "Cartera Terracota Minimal", precio: 27.99, img: "img/reales/cartera-real-14.jpg", categoria: "hombro", nuevo: true },
  { id: 26, nombre: "Mini Clutch Colección Pastel", precio: 24.50, img: "img/reales/cartera-real-15.jpg", categoria: "mini", nuevo: true },
  { id: 27, nombre: "Cartera Fucsia Tropical", precio: 29.50, img: "img/cartera23.svg", categoria: "hombro", nuevo: true },
  { id: 28, nombre: "Satchel Cielo Elegante", precio: 33.99, img: "img/cartera24.svg", categoria: "satchel", nuevo: true },
  { id: 29, nombre: "Bandolera Menta Urbana", precio: 27.99, img: "img/cartera25.svg", categoria: "bandolera", nuevo: true },
  { id: 30, nombre: "Bucket Bag Ámbar Otoño", precio: 30.99, img: "img/cartera26.svg", categoria: "bucket", nuevo: true },
  { id: 31, nombre: "Mini Bolso Lavanda Dulce", precio: 22.99, img: "img/cartera27.svg", categoria: "mini", nuevo: true },
  { id: 32, nombre: "Clutch Rubí Noche", precio: 28.99, img: "img/cartera28.svg", categoria: "clutch", nuevo: true },
  { id: 33, nombre: "Tote Oliva Casual", precio: 24.50, img: "img/cartera29.svg", categoria: "tote", nuevo: true },
  { id: 34, nombre: "Cartera Cobre Vintage", precio: 31.50, img: "img/cartera30.svg", categoria: "hombro", nuevo: true },
];
